---
driver:
  name: docker
  hostname: neutron.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: neutron
  grains:
    noservices: True
  vendor_repo:
    - type: apt
      url: http://apt-mk.mirantis.com/trusty
      key_url: http://apt-mk.mirantis.com/public.gpg
      components: oc303 extra
      distribution: nightly
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - linux.system
        - neutron
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_openstack
          - neutron
  pillars-from-files:
    linux_repo_openstack.sls: tests/pillar/repo_mos9.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: compute_dpdk
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_dpdk.sls

  - name: compute_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_dvr.sls

  - name: compute_legacy
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_legacy.sls

  - name: compute_nonexternal_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_nonexternal_dvr.sls

  - name: compute_sriov
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/compute_sriov.sls

  - name: control_cluster
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_cluster.sls

  - name: control_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_dvr.sls

  - name: control_nodvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_nodvr.sls

  - name: control_single
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/control_single.sls

  - name: gateway_dvr
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_dvr.sls

  - name: gateway_legacy
    provisioner:
      pillars-from-files:
        neutron.sls: tests/pillar/gateway_legacy.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
